combine start/enable service in one line
kibatic/ansible-traefik pull request #13
Opened 2017-03-11 23:25 UTC by sjourdan

2017-03-13 21:01 UTC, sjourdan commented
cleaner PR

2017-03-14 08:43 UTC, eliecharra requested changes

2017-03-14 08:43 UTC, eliecharra commented on tasks/main.yml
> +  service: name=traefik state=started enabled=yes
@sjourdan Could you remove task inline config (name=...) and put each option on a single line to be ?

To be more homogenous with the rest of the role.

2017-03-24 08:52 UTC, eliecharra commented
I merge this, will fix style in master

2017-03-24 08:52 UTC, eliecharra approved these changes

2017-03-24 08:52 UTC, merged